# Generated by Django 3.2.19 on 2023-05-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('application_status', models.CharField(choices=[('CREATED', 'Створена'), ('PROCESSING', 'В обробці'), ('FAILED', 'Помилка обробки'), ('ON_REVIEW', 'Подана на розгляд'), ('EXECUTED', 'Виконана'), ('REJECTED', 'Запит відхилено')], default='CREATED', max_length=20, verbose_name='Статус заявки')),
                ('applicant_unique_code', models.CharField(blank=True, help_text='Подається разом з заявою', max_length=10, null=True, verbose_name='Код РНОКПП заявника')),
                ('failure_reason', models.CharField(blank=True, help_text='Помилка отримання даних від міністерства', max_length=255, null=True, verbose_name='Причина помилки')),
                ('сertificate_no', models.CharField(blank=True, help_text='Генерується автоматично при підтвердженні заявки', max_length=255, null=True, verbose_name='Унікальний номер довідки')),
                ('applicant_fullname', models.CharField(blank=True, help_text='Заповнюється за запитом до міністерства автоматично', max_length=255, null=True, verbose_name="Повне ім'я заявника")),
                ('applicant_home_address', models.CharField(blank=True, help_text='Заповнюється за запитом до міністерства автоматично', max_length=512, null=True, verbose_name='Домашня адреса')),
                ('applicant_medical_ensurance', models.CharField(blank=True, help_text='Заповнюється за запитом до міністерства автоматично', max_length=512, null=True, verbose_name='Номер та дата медичного страхування')),
                ('created_at', models.DateTimeField(verbose_name='Дата створення заявки')),
                ('updated_at', models.DateTimeField(verbose_name='Дата оновлення інформації про заявку')),
            ],
            options={
                'verbose_name': 'Довідка',
                'verbose_name_plural': 'Довідки',
                'ordering': ['id'],
            },
        ),
    ]
