# Generated by Django 3.2.19 on 2023-05-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення заявки'),
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення інформації про заявку'),
        ),
    ]
