# Generated by Django 3.2.19 on 2023-05-31 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnap', '0002_auto_20230531_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateapplication',
            name='application_file',
            field=models.FileField(blank=True, help_text='У вигляді файлу', max_length=512, null=True, upload_to='', verbose_name='Заявка в форматі PDF'),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_file', models.FileField(max_length=500, null=True, upload_to='', verbose_name='Файл')),
                ('title', models.CharField(db_index=True, default='', max_length=100, verbose_name='Назва')),
                ('create_date', models.DateField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата створення документа')),
                ('request_trigger', models.CharField(choices=[('0', 'Довідка про медичне страхування')], db_index=True, error_messages={'unique': 'Шаблон цієї заявки вже існує!'}, max_length=100, unique=True, verbose_name='Предмет заявки')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблони',
            },
        ),
    ]
